# Generated by Django 5.1.6 on 2025-02-13 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('GBP', 'Libra esterlina'), ('JPY', 'Yen japonés'), ('MXN', 'Peso mexicano'), ('CAD', 'Dólar canadiense'), ('AUD', 'Dólar australiano'), ('CHF', 'Franco suizo'), ('CNY', 'Yuan chino'), ('SEK', 'Corona sueca')], default='USD', max_length=3)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('transa_ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('proceso', 'Proceso'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('revertida', 'Revertida')], default='proceso', max_length=20)),
                ('from_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='accounts.account')),
                ('to_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='accounts.account')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Transacciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
